cli:./build
	gcc -o ./build/cli cli.c

uppercase:./build
	gcc -o ./build/uppercase uppercase.c

reverse:./build
	gcc -o ./build/reverse reverse.c

all:./build
	gcc -o ./build/uppercase uppercase.c
	gcc -o ./build/cli cli.c
	gcc -o ./build/reverse reverse.c

build:
	mkdir build

clean:
	rm ./build/* 
